# Fly.io configuration for Tailscale Exit Node - Single Machine Only
# Note: app and primary_region will be updated dynamically during deployment
app = "tailscale-exit-node"
primary_region = "fra"

[build]
dockerfile = "Dockerfile"

[env]
PATH = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Enable init system for proper process handling
init = true

# Enable console access for state extraction
[console]
guest = true

# Deployment strategy to ensure single machine only
[deploy]
  strategy = "immediate"     # Replace machine immediately, no rolling deployment
  max_unavailable = 1        # Allow only 1 machine to be unavailable during deploy

# Explicitly configure for single machine to stay on free tier
[[vm]]
  size = "shared-cpu-1x"     # Free tier size
  memory = "256mb"           # Minimum memory to stay free
