# Fly.io configuration for Tailscale Exit Node
# Note: app and primary_region will be updated dynamically during deployment
app = "tailscale-exit-node"
primary_region = "fra"

[build]
dockerfile = "Dockerfile"

[env]
PATH = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Enable init system for proper process handling
init = true

# Enable console access for state extraction
[console]
guest = true