name: Destroy Exit Node

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Destroy Exit Node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          APP_NAME: ${{ secrets.APP_NAME }}
        run: |
          if flyctl status --app "$APP_NAME" &> /dev/null; then
            echo "Destroying app: $APP_NAME"
            flyctl apps destroy "$APP_NAME" --yes
            echo "✅ App destroyed successfully"
          else
            echo "❌ App $APP_NAME does not exist"
          fi